//! VPN tunnel relay — drives the native PPP state machine.
//!
//! Flow: gateway <--tunnel framing--> PppState <--raw IP--> TUN device.

use crate::engine::hdlc;
use crate::engine::pppstate::{Phase, PppState, PROTO_IPV4};
use std::io::{self, Read, Write};
#[cfg(test)]
use std::collections::VecDeque;
use std::net::Ipv4Addr;
use std::os::fd::RawFd;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

const READ_BUF: usize = 16384;

/// Negotiation must reach the NETWORK phase within this window, or we abort
/// instead of showing "Connecting…" forever when the gateway stalls.
const NEGOTIATION_TIMEOUT: Duration = Duration::from_secs(25);
/// LCP keepalive interval once the link is up.
const ECHO_INTERVAL: Duration = Duration::from_secs(10);
/// Abort if queued output makes no progress for this long (gateway stalled).
const WRITE_STALL_TIMEOUT: Duration = Duration::from_secs(30);
/// rustls' limit for unsent TLS records (its default, set explicitly). The
/// outbound backlog is bounded by MAX_QUEUED + TLS_SEND_BUFFER (~576 KiB).
pub const TLS_SEND_BUFFER: usize = 64 * 1024;
/// Stop reading from TUN while this much output is queued (backpressure:
/// the kernel then queues/drops, TCP inside the tunnel slows down).
const MAX_QUEUED: usize = 512 * 1024;
/// Hard cap on queued outbound bytes, control frames included. TUN reads stop
/// at MAX_QUEUED, but PPP control replies are generated by the peer's traffic;
/// a peer that floods requests without reading our replies ends the tunnel
/// here instead of growing memory without bound.
const MAX_OUT_BYTES: usize = 2 * 1024 * 1024;
/// Consecutive TUN write failures before the tunnel is declared broken.
const MAX_TUN_WRITE_FAILURES: u32 = 200;
/// Max TUN packets forwarded per loop pass (bounded so TLS reads aren't starved).
const TUN_BATCH: usize = 64;
/// Don't send keepalives while more than this much output is queued.
const ECHO_MAX_BACKLOG: usize = 16 * 1024;
/// After this long in NETWORK with outbound but zero inbound IP, warn loudly.
const NO_REPLY_WARN_AFTER: Duration = Duration::from_secs(15);

/// File descriptors of the transport and TUN device, used to sleep in
/// poll(2) instead of busy-waiting. `None` (tests) falls back to short sleeps.
#[derive(Clone, Copy)]
pub struct RelayFds {
    pub tls: RawFd,
    pub tun: RawFd,
}

/// Non-blocking transport to the gateway, with reads and writes fully
/// decoupled. (`rustls::StreamOwned::read` flushes pending writes *before*
/// returning plaintext, so under send backpressure received data would be
/// stranded; driving the connection directly avoids that.)
pub trait Transport {
    /// Next decrypted bytes: Ok(0) = connection closed, WouldBlock = none yet.
    fn recv(&mut self, buf: &mut [u8]) -> io::Result<usize>;
    /// Hand plaintext to the TLS layer; may accept fewer bytes (0 when full).
    fn send(&mut self, data: &[u8]) -> io::Result<usize>;
    /// Write buffered ciphertext to the socket; returns bytes written.
    fn push(&mut self) -> io::Result<usize>;
    /// Whether ciphertext is still waiting for the socket.
    fn has_pending(&self) -> bool;
}

impl Transport for rustls::StreamOwned<rustls::ClientConnection, std::net::TcpStream> {
    fn recv(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        loop {
            match self.conn.reader().read(buf) {
                Ok(n) => return Ok(n), // 0 = clean close_notify
                Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => {}
                Err(e) => return Err(e),
            }
            // No plaintext buffered: pull more ciphertext (never writes).
            match self.conn.read_tls(&mut self.sock)? {
                0 => return Ok(0), // TCP EOF
                _ => {
                    self.conn.process_new_packets()
                        .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;
                }
            }
        }
    }

    fn send(&mut self, data: &[u8]) -> io::Result<usize> {
        self.conn.writer().write(data)
    }

    fn push(&mut self) -> io::Result<usize> {
        let mut written = 0;
        while self.conn.wants_write() {
            match self.conn.write_tls(&mut self.sock) {
                Ok(0) => break,
                Ok(n) => written += n,
                Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => break,
                Err(ref e) if e.kind() == io::ErrorKind::Interrupted => {}
                Err(e) => return Err(e),
            }
        }
        Ok(written)
    }

    fn has_pending(&self) -> bool {
        self.conn.wants_write()
    }
}

/// Traffic counters, logged when the relay stops.
#[derive(Default, Debug)]
struct Stats {
    frames_in: u64,
    ip_in: u64,
    ip_out: u64,
    tun_write_errors: u64,
}

/// Plaintext waiting to be accepted by the TLS layer.
struct OutQueue {
    buf: Vec<u8>,
    last_progress: Instant,
}

impl OutQueue {
    fn new() -> Self {
        Self { buf: Vec::new(), last_progress: Instant::now() }
    }

    /// Queue a framed packet, enforcing the hard `MAX_OUT_BYTES` cap.
    fn push(&mut self, frame: &[u8]) -> Result<(), String> {
        if self.buf.len() + frame.len() > MAX_OUT_BYTES {
            return Err(format!(
                "outbound queue exceeded {} KiB — the gateway is not reading our traffic", MAX_OUT_BYTES / 1024));
        }
        self.buf.extend_from_slice(frame);
        Ok(())
    }

    fn has_work(&self, t: &impl Transport) -> bool {
        !self.buf.is_empty() || t.has_pending()
    }

    /// Move queued plaintext into TLS and ciphertext onto the socket, without
    /// blocking. Returns whether any bytes reached the socket.
    fn pump(&mut self, t: &mut impl Transport) -> io::Result<bool> {
        loop {
            if !self.buf.is_empty() {
                let n = t.send(&self.buf)?;
                self.buf.drain(..n);
            }
            let wrote = t.push()?;
            if wrote > 0 {
                self.last_progress = Instant::now();
            }
            // Keep going while the socket takes data and we have more to give.
            if wrote == 0 || self.buf.is_empty() && !t.has_pending() {
                if !self.has_work(t) {
                    self.last_progress = Instant::now();
                }
                return Ok(wrote > 0);
            }
        }
    }

    /// Output pending but the socket accepted nothing for the whole window.
    fn stalled(&self, t: &impl Transport) -> bool {
        self.has_work(t) && self.last_progress.elapsed() > WRITE_STALL_TIMEOUT
    }
}

/// Run the relay until disconnect (Ok) or a failure (Err with the reason).
///
/// `on_network` is invoked exactly once, when IPCP completes, with the
/// negotiated PPP state; it applies the IP/MTU/routes. If it fails the tunnel
/// is torn down with that error.
#[allow(clippy::too_many_arguments)]
pub fn run_relay(
    mut tls: impl Transport,
    mut tun_w: impl Write,
    mut tun_r: impl Read,
    fds: Option<RelayFds>,
    local_ip: Ipv4Addr,
    log_tx: Option<std::sync::mpsc::Sender<String>>,
    stop: Arc<AtomicBool>,
    mut on_network: impl FnMut(&PppState) -> Result<(), String>,
) -> Result<(), String> {
    let log = |msg: &str| {
        log::info!("{}", msg);
        if let Some(ref tx) = log_tx { let _ = tx.send(msg.to_string()); }
    };

    let magic = (SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_nanos() & 0xFFFF_FFFF) as u32;
    let mut ppp = PppState::new(local_ip, magic);

    let mut out = OutQueue::new();

    // Kick off LCP negotiation.
    ppp.start();
    queue_outbox(&mut ppp, &mut out)?;
    out.pump(&mut tls).map_err(|e| format!("PPP: failed to send LCP request: {}", e))?;
    log("PPP: LCP Configure-Request sent, negotiating…");

    let mut tmp = vec![0u8; READ_BUF];
    let mut acc: Vec<u8> = Vec::with_capacity(READ_BUF);
    let mut stats = Stats::default();
    let started = Instant::now();
    let mut network_since: Option<Instant> = None;
    let mut last_echo = Instant::now();
    let mut warned_no_reply = false;
    let mut tun_fail_streak = 0u32;

    let result: Result<(), String> = 'relay: loop {
        if stop.load(Ordering::Relaxed) {
            log("Disconnect requested — closing tunnel.");
            break Ok(());
        }
        if ppp.phase != Phase::Network && started.elapsed() > NEGOTIATION_TIMEOUT {
            break Err("PPP negotiation timed out — the gateway did not complete LCP/IPCP.".into());
        }
        let mut did_work = false;

        // --- gateway → PPP ---
        match tls.recv(&mut tmp) {
            Ok(0) => break Err("the gateway closed the TLS connection".into()),
            Ok(n) => {
                did_work = true;
                acc.extend_from_slice(&tmp[..n]);

                // Guard against an HTTP error reply where a PPP frame is expected.
                if acc.len() >= 6 && &acc[..6] == b"HTTP/1" {
                    break Err("Gateway returned HTTP instead of a PPP frame — tunnel mode likely not allowed (check realm).".into());
                }

                // Pop every complete frame currently buffered.
                while let Some((frame, consumed)) = hdlc::pop_frame(&acc) {
                    acc.drain(..consumed);
                    if frame.len() < 2 { continue; } // bad header / runt frame
                    stats.frames_in += 1;
                    // Any traffic from the gateway proves the link is alive, so a
                    // saturated send queue can't make queued echoes look lost.
                    ppp.echo_outstanding = 0;
                    let proto = u16::from_be_bytes([frame[0], frame[1]]);
                    if proto != PROTO_IPV4 {
                        log(&format!("PPP recv proto=0x{:04x} code={} len={} phase={:?}",
                            proto, frame.get(2).copied().unwrap_or(0), frame.len(), ppp.phase));
                    }
                    if let Some(ip) = ppp.handle(&frame) {
                        stats.ip_in += 1;
                        match tun_w.write_all(&ip) {
                            Ok(()) => tun_fail_streak = 0,
                            Err(e) => {
                                stats.tun_write_errors += 1;
                                tun_fail_streak += 1;
                                if stats.tun_write_errors <= 5 {
                                    log(&format!("WARNING: TUN write failed ({}), packet dropped", e));
                                }
                                if tun_fail_streak >= MAX_TUN_WRITE_FAILURES {
                                    break 'relay Err(format!(
                                        "the TUN device stopped accepting packets ({})", e));
                                }
                            }
                        }
                    }
                    for w in ppp.warnings.drain(..) {
                        log(&format!("WARNING: PPP: {}", w));
                    }
                }
                if let Err(e) = queue_outbox(&mut ppp, &mut out) {
                    break Err(e);
                }

                if ppp.phase == Phase::Dead {
                    // Best-effort: deliver our Terminate-Ack before closing.
                    let _ = out.pump(&mut tls);
                    break Err(ppp.dead_reason.clone().unwrap_or_else(|| "PPP link terminated".into()));
                }
                if ppp.phase == Phase::Network && network_since.is_none() {
                    log(&format!("PPP: NETWORK phase reached (IP {}, peer MRU {:?})",
                        ppp.local_ip, ppp.peer_mru));
                    if let Err(e) = on_network(&ppp) {
                        break Err(e);
                    }
                    network_since = Some(Instant::now());
                    last_echo = Instant::now();
                }
            }
            Err(ref e) if e.kind() == io::ErrorKind::WouldBlock || e.kind() == io::ErrorKind::Interrupted => {}
            Err(e) => break Err(format!("TLS read error: {}", e)),
        }

        // --- TUN → gateway (only once IP is up, and while the queue has room) ---
        if ppp.phase == Phase::Network {
            for _ in 0..TUN_BATCH {
                if out.buf.len() >= MAX_QUEUED { break; }
                match tun_r.read(&mut tmp) {
                    Ok(0) => break,
                    Ok(n) => {
                        did_work = true;
                        if tmp[0] >> 4 != 4 { continue; } // IPv4 only (IPV6CP is rejected)
                        if let Err(e) = out.push(&hdlc::frame_packet(&tmp[..n])) {
                            break 'relay Err(e);
                        }
                        stats.ip_out += 1;
                    }
                    Err(ref e) if e.kind() == io::ErrorKind::WouldBlock || e.kind() == io::ErrorKind::Interrupted => break,
                    Err(e) => break 'relay Err(format!("TUN read error: {}", e)),
                }
            }

            // Keepalive: detects a gateway that silently stopped forwarding.
            // Skip while a large backlog is queued: a probe would sit behind it
            // and look unanswered although the gateway is healthy.
            if last_echo.elapsed() >= ECHO_INTERVAL && out.buf.len() < ECHO_MAX_BACKLOG {
                last_echo = Instant::now();
                if !ppp.send_echo_request() {
                    break Err(ppp.dead_reason.clone().unwrap_or_else(|| "LCP keepalive failed".into()));
                }
                if let Err(e) = queue_outbox(&mut ppp, &mut out) {
                    break Err(e);
                }
            }

            if !warned_no_reply
                && stats.ip_in == 0
                && stats.ip_out > 0
                && network_since.map(|t| t.elapsed() > NO_REPLY_WARN_AFTER).unwrap_or(false)
            {
                warned_no_reply = true;
                log(&format!(
                    "WARNING: sent {} packets into the tunnel but received none back — the gateway \
                     is not returning traffic (check the assigned IP / firewall policy).", stats.ip_out));
            }
        }

        // --- drain queued output without blocking ---
        match out.pump(&mut tls) {
            Ok(true) => did_work = true,
            Ok(false) => {}
            Err(e) => break Err(format!("TLS write failed: {}", e)),
        }
        if out.stalled(&tls) {
            break Err(format!("the gateway stopped accepting data for {}s", WRITE_STALL_TIMEOUT.as_secs()));
        }

        if !did_work {
            let want_tun = ppp.phase == Phase::Network && out.buf.len() < MAX_QUEUED;
            wait_for_io(fds, want_tun, out.has_work(&tls));
        }
    };

    log(&format!(
        "Relay stopped: {} frames in, {} IP packets in, {} IP packets out, {} TUN write errors",
        stats.frames_in, stats.ip_in, stats.ip_out, stats.tun_write_errors));
    result
}

/// Sleep until the TLS socket is readable (or writable, while output is
/// queued), or the TUN device is readable, or a short timeout elapses so
/// stop/keepalive checks still run.
fn wait_for_io(fds: Option<RelayFds>, include_tun: bool, want_write: bool) {
    match fds {
        Some(fds) => {
            let tls_events = libc::POLLIN | if want_write { libc::POLLOUT } else { 0 };
            let mut pfds = [
                libc::pollfd { fd: fds.tls, events: tls_events, revents: 0 },
                libc::pollfd { fd: fds.tun, events: libc::POLLIN, revents: 0 },
            ];
            let n = if include_tun { 2 } else { 1 };
            unsafe { libc::poll(pfds.as_mut_ptr(), n, 200); }
        }
        None => std::thread::sleep(Duration::from_millis(2)),
    }
}

/// Queue all pending PPP frames (with tunnel framing) for sending.
fn queue_outbox(ppp: &mut PppState, out: &mut OutQueue) -> Result<(), String> {
    for frame in ppp.outbox.drain(..) {
        out.push(&hdlc::frame_raw(&frame))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Transport whose socket accepts `cap` bytes per push and whose TLS
    /// layer buffers at most 8 bytes of plaintext.
    struct MockTransport { tls_buf: Vec<u8>, wire: Vec<u8>, cap: usize, inbound: VecDeque<u8> }
    impl Transport for MockTransport {
        fn recv(&mut self, buf: &mut [u8]) -> io::Result<usize> {
            if self.inbound.is_empty() { return Err(io::ErrorKind::WouldBlock.into()); }
            let n = buf.len().min(self.inbound.len());
            for b in buf.iter_mut().take(n) { *b = self.inbound.pop_front().unwrap(); }
            Ok(n)
        }
        fn send(&mut self, data: &[u8]) -> io::Result<usize> {
            let n = data.len().min(8 - self.tls_buf.len());
            self.tls_buf.extend_from_slice(&data[..n]);
            Ok(n)
        }
        fn push(&mut self) -> io::Result<usize> {
            let n = self.tls_buf.len().min(self.cap);
            self.wire.extend(self.tls_buf.drain(..n));
            Ok(n)
        }
        fn has_pending(&self) -> bool { !self.tls_buf.is_empty() }
    }

    #[test]
    fn queue_has_a_hard_cap_for_all_frames() {
        // Regression (Copilot): PPP control replies bypassed the queue limit.
        let mut q = OutQueue::new();
        let chunk = vec![0u8; 64 * 1024];
        for _ in 0..(MAX_OUT_BYTES / chunk.len()) {
            q.push(&chunk).unwrap();
        }
        assert!(q.push(&[0u8; 1]).is_err(), "overflow is an error, not silent growth");
        assert_eq!(q.buf.len(), MAX_OUT_BYTES);
        // Control replies go through the same cap.
        let mut ppp = PppState::new(Ipv4Addr::new(10, 0, 0, 1), 1);
        ppp.outbox.push(vec![0xC0, 0x21, 10, 1, 0, 8, 0, 0, 0, 1]);
        assert!(queue_outbox(&mut ppp, &mut q).is_err());
    }

    #[test]
    fn queue_drains_through_small_buffers() {
        let mut t = MockTransport { tls_buf: vec![], wire: vec![], cap: 3, inbound: VecDeque::new() };
        let mut q = OutQueue::new();
        q.buf.extend_from_slice(b"hello world, tunnel");
        assert!(q.pump(&mut t).unwrap());
        assert!(!q.has_work(&t));
        assert_eq!(t.wire, b"hello world, tunnel");
    }

    #[test]
    fn blocked_socket_keeps_data_and_is_not_progress() {
        let mut t = MockTransport { tls_buf: vec![], wire: vec![], cap: 0, inbound: VecDeque::new() };
        let mut q = OutQueue::new();
        q.buf.extend_from_slice(b"0123456789");
        assert!(!q.pump(&mut t).unwrap());
        assert!(q.has_work(&t));
        assert_eq!(q.buf.len() + t.tls_buf.len(), 10);
        // Reading is independent of the blocked writes.
        t.inbound.extend(b"in".iter().copied());
        let mut b = [0u8; 4];
        assert_eq!(t.recv(&mut b).unwrap(), 2);
    }
}
